#! /bin/bash

target=`pwd`
bt=~/minecraft/buildtools
temp=~/temp

function update () {
	mkdir -p $bt
	if [ -e $bt/BuildTools.jar ] ; then
		rm -f $bt/BuildTools.jar
	fi
	curl "https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar" -o $bt/BuildTools.jar
}

function build () {
	mkdir -p $temp
	cd $temp
	if [ "$rev" == "" ] ; then
		java -jar $bt/BuildTools.jar
	else
		java -jar $bt/BuildTools.jar --rev $rev
	fi
}

case $1 in
	update)
		update
	;;
	build)
		rev="$2"
		update
		build

		mv $temp/*.jar $target
		rm -rf $temp
	;;
	*)
		echo "$0 usage: $0 update"
		echo "$0 usage: $0 build"
		echo "$0 usage: $0 build rev#"
		echo "e.g. $0 build 1.12.2"
	;;
esac
